//Form Schema
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var formSchema = new Schema({
    capitulo: "String",
    cidade: "String",
    loja: "String",
    dados:"String",
    endereco: "String",
    email: "String",
    pagina: "String",
    grupo: "String",
    sede: "String",
    relacao: "String",
    participacao: "String",
    regimento: "String",
    obrigatoriedade: "String",
    quantidade: "String",
    idade: "String",
    menos16: "String",
    maconsp: "String",
    avcons: "String",
    ajuda: "String",
    comissao: "String",
    relatorio: "String",
    modelo: "String",
    reunioes: "String",
    tempoinic: "String",
    inics: "String",
    iniciados: "String",
    beneficentes:"String",
    instrucoesinic:"String",
    mat_inst_inic:"String",
    instrucoesdm:"String",
    mat_inst_DM:"String",
    pratrit:"String",
    avrit:"String",
    avinst:"String",
    livros:"String",
    arquivos:"String",
    prestacao:"String",
    mensalidade:"String",
    conhecetavola:"String",
    interessetavola:"String",
    patrocinartavola:"String",
    conventos:"String",
    cavativos:"String",
    cavreq:"String",
    motiv_nao_cav:"String",
    cavincen:"String",
    relacao_conv:"String",
    icc_visit:"String",
    caixa_cap:"String",
    rec_cid:"String",
    evasao:"String",
    motiv_afast:"String",
    atividades:"String",
    temas:"String",
    int_treinamentos:"String",
    area_treinamentos:"String",
    habil_gestao:"String",
    areas_melhorar:"String",
    como_ajudar:"String",
    usuario: {
      id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
      },
      nome: String
    }
});
var Form = mongoose.model('Form', formSchema);
module.exports = Form;
